server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Fallback para o index.html (importante para o React Router/Vite)
        try_files $uri $uri/ /index.html;
    }

    # Redireciona erros de servidor para a página 50x
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
